name: Deploy Monorepo (Client & Server)
on:
    push:
        branches:
            - main
        
jobs:
    deploy-client:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4

            - name: Install & Build Client
              run: |
                cd apps/client
                npm ci
                npm run build

            - name: Deploy ke github pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{secrets.GITHUB_TOKEN}}
                publish_dir: ./apps/client/dist

    deploy-server:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install & Deploy ke Cloudflare Pages
              uses: cloudflare/wrangler-action@v3
              with:
                apiToken: ${{secrets.CLOUDFLARE_API_TOKEN}}
                workingDirectory: 'apps/server'
                command: deploy